sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
      - master
notifications:
  email: false
node_js:
  - 6.9.4
before_install:
  - npm i -g npm@^3.10.10
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
install: npm install